package server

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/kayushkin/llm-bridge-server/internal/config"
	"github.com/kayushkin/llm-bridge-server/internal/store"
	"github.com/kayushkin/llm-bridge-server/internal/textutil"
	"github.com/kayushkin/llm-bridge/msg"
)

// The session renamer gives a session whose name nobody chose a sidebar title
// drawn from its recent turns: one routed one-shot call on the
// session_renamer.model_role role. Until 2026-09-30 it started a whole Claude
// Code session on the target's own instance, with no model named, which told
// the new session to curl its title back — about a hundred sessions a week,
// each on whatever model the harness defaulted to.

const (
	// renameFirstAfter triggers the very first auto-rename pass once a session
	// has at least this many user messages. Two gives the namer a real
	// assistant turn of context to draw from rather than just the truncated
	// first line.
	renameFirstAfter = 2
	// renameEvery is the cadence (in user messages) for re-checking the title
	// after the first run, so long-running sessions get a fresh name as the
	// topic drifts.
	renameEvery = 10
	// recentTurnsForRename caps how many turns of transcript get included in
	// the renamer's prompt. Each text is also truncated by the store helper.
	recentTurnsForRename = 12
	// renamerSourceTag is the purpose the renamer's own sessions carried
	// before it became a one-shot call. Their rows remain, and their turns
	// are still neither renamed nor classified.
	renamerSourceTag = "renamer"
	// renamerSlotPrefix starts the id a title call reserves the target's
	// renamer slot under.
	renamerSlotPrefix = "rename-call-"
	// renamerTimeout bounds one title call, fallbacks included.
	renamerTimeout = 2 * time.Minute
	// renamerMaxTokens bounds the title call's answer.
	renamerMaxTokens = 256
	// maxAutoRenameRunes caps the rune length of an auto-generated title.
	// Sized for the sidebar at 100% zoom (~18 average-width characters fit;
	// allow a few more to accommodate narrow letters before truncating).
	maxAutoRenameRunes = 24
)

// renamerTitleSchema forces the title call's answer into one field.
var renamerTitleSchema = json.RawMessage(`{
  "type": "object",
  "properties": {"title": {"type": "string"}},
  "required": ["title"],
  "additionalProperties": false
}`)

const renamerSystemPrompt = `You write the sidebar title of a chat session from its transcript. Say what the session is about — its topic, task or problem — not its literal first message. The sidebar is narrow: aim for about 18 characters, never more than 24. Prefer a short noun phrase ("auth bug fix", "deploy script") to a sentence. No quotes.`

// applyAutoRename stores a title the renamer wrote, if slot still holds the
// session's renamer slot, and tells connected clients. A slot the user
// cleared by renaming the session by hand leaves the name alone.
func (s *Server) applyAutoRename(bridgeID, slot, title string) error {
	name := textutil.TruncateToRuneLimit(strings.TrimSpace(title), maxAutoRenameRunes)
	if name == "" {
		return fmt.Errorf("the title is empty")
	}
	turnCount, err := s.store.CountUserMessages(bridgeID)
	if err != nil {
		return fmt.Errorf("count user messages: %w", err)
	}
	if err := s.store.ApplyAutoRename(bridgeID, slot, name, turnCount); err != nil {
		return fmt.Errorf("store the title: %w", err)
	}
	sess, err := s.store.GetSession(bridgeID)
	if err != nil {
		return fmt.Errorf("read the renamed session: %w", err)
	}
	s.broadcastDisplayNameChanged(bridgeID, sess.DisplayName)
	return nil
}

// broadcastDisplayNameChanged emits a system event on the target session's
// SSE stream so connected clients can refresh their session list without
// waiting for the next turn or page reload. Best-effort; logs and continues
// on failure.
func (s *Server) broadcastDisplayNameChanged(bridgeID, displayName string) {
	ev := msg.Event{
		Type:            msg.EventSystem,
		BridgeSessionID: bridgeID,
		Timestamp:       time.Now(),
		System: &msg.SystemEvent{
			Subtype: "display_name_changed",
			Message: displayName,
		},
	}
	if _, err := s.harness.BroadcastEvent(&ev); err != nil {
		log.Printf("[rename] %s: broadcast display_name_changed: %v", bridgeID, err)
	}
}

// maybeAutoRename inspects the target session and, when conditions are met,
// asks the renamer role for a sidebar title and stores it. Always called as a
// goroutine — long-running, must never block the /send response.
//
// Conditions to fire:
//   - session_renamer.model_role is set
//   - Purpose != "renamer"  (a helper session from before the one-shot renamer)
//   - display_name is autogenerated (user hasn't manually renamed)
//   - no title call is already in flight for this target
//   - first run: turn_count >= renameFirstAfter
//   - subsequent runs: turn_count - named_at_turn >= renameEvery
func (s *Server) maybeAutoRename(bridgeID string) {
	modelRole := s.settings.ModelRole(config.SettingSessionRenamerModelRole)
	if modelRole == "" {
		return
	}
	target, err := s.store.GetSession(bridgeID)
	if err != nil {
		return
	}
	if target.Purpose == renamerSourceTag {
		return
	}

	autogen, namedAtTurn, inFlight, err := s.store.RenamerState(bridgeID)
	if err != nil {
		log.Printf("[renamer] %s: state lookup: %v", bridgeID, err)
		return
	}
	if !autogen {
		return
	}
	if inFlight != "" {
		if s.renamerStillAlive(inFlight) {
			return
		}
		// A slot no call in this process holds was left by a call a restart
		// killed, or by a renamer session from before the one-shot renamer.
		if err := s.store.ClearRenamerSlot(bridgeID); err != nil {
			log.Printf("[renamer] %s: clear stale slot: %v", bridgeID, err)
			return
		}
	}

	turnCount, err := s.store.CountUserMessages(bridgeID)
	if err != nil {
		log.Printf("[renamer] %s: count user messages: %v", bridgeID, err)
		return
	}
	threshold := renameEvery
	if namedAtTurn == 0 {
		threshold = renameFirstAfter
	}
	if turnCount-namedAtTurn < threshold {
		return
	}

	turns, err := s.harness.RecentTurnTexts(bridgeID, recentTurnsForRename)
	if err != nil {
		log.Printf("[renamer] %s: load transcript: %v", bridgeID, err)
		return
	}
	if len(turns) == 0 {
		return
	}

	if err := s.renameFromTranscript(target, turns, modelRole); err != nil {
		log.Printf("[renamer] %s: %v", bridgeID, err)
	}
}

// renamerStillAlive reports whether a title call in this process holds the
// slot.
func (s *Server) renamerStillAlive(slot string) bool {
	_, running := s.renamesInFlight.Load(slot)
	return running
}

// renameFromTranscript reserves the target's renamer slot, asks modelRole for
// a title, and stores it. Losing the slot to another call is not an error.
func (s *Server) renameFromTranscript(target *store.Session, turns []store.TurnText, modelRole string) error {
	slot := renamerSlotPrefix + generateBridgeID()
	reserved, err := s.store.ReserveRenamerSlot(target.SessionID, slot)
	if err != nil {
		return fmt.Errorf("reserve slot: %w", err)
	}
	if !reserved {
		return nil
	}
	s.renamesInFlight.Store(slot, true)
	defer s.renamesInFlight.Delete(slot)

	ctx, cancel := context.WithTimeout(context.Background(), renamerTimeout)
	defer cancel()
	reply, err := s.oneShotRouter.RunRole(ctx, msg.OneShotRequest{
		Prompt:       buildRenamerPrompt(target, turns),
		SystemPrompt: renamerSystemPrompt,
		ModelRole:    modelRole,
		Caller:       oneShotCallerSessionRenamer,
		Schema:       renamerTitleSchema,
		MaxTokens:    renamerMaxTokens,
	})
	if err == nil && len(reply.Parsed) == 0 {
		err = fmt.Errorf("%s answered with no title (stop reason %q)", reply.Model, reply.StopReason)
	}
	var answer struct {
		Title string `json:"title"`
	}
	if err == nil {
		err = json.Unmarshal(reply.Parsed, &answer)
	}
	if err == nil {
		err = s.applyAutoRename(target.SessionID, slot, answer.Title)
	}
	if err != nil {
		if clearErr := s.store.ClearRenamerSlot(target.SessionID); clearErr != nil {
			log.Printf("[renamer] %s: clear slot after a failed title: %v", target.SessionID, clearErr)
		}
		return fmt.Errorf("title: %w", err)
	}
	log.Printf("[renamer] %s: titled by %s on %s (turns=%d)", target.SessionID, reply.Model, reply.InstanceID, len(turns))
	return nil
}

// buildRenamerPrompt is the transcript the title is written from.
func buildRenamerPrompt(target *store.Session, turns []store.TurnText) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Current title: %q\n\nTranscript (oldest first):\n---\n", target.DisplayName)
	for i, t := range turns {
		fmt.Fprintf(&b, "Turn %d\n", i+1)
		if t.User != "" {
			fmt.Fprintf(&b, "USER: %s\n", t.User)
		}
		if t.Assistant != "" {
			fmt.Fprintf(&b, "ASSISTANT: %s\n", t.Assistant)
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n")
	return b.String()
}
