package server

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/kayushkin/llm-bridge-server/internal/store"
	"github.com/kayushkin/llm-bridge/msg"
)

const (
	// renameFirstAfter triggers the very first auto-rename pass once a session
	// has at least this many user messages. Two gives the namer a real
	// assistant turn of context to draw from rather than just the truncated
	// first line.
	renameFirstAfter = 2
	// renameEvery is the cadence (in user messages) for re-checking the title
	// after the first run, so long-running sessions get a fresh name as the
	// topic drifts.
	renameEvery = 10
	// recentTurnsForRename caps how many turns of transcript get included in
	// the renamer's prompt. Each text is also truncated by the store helper.
	recentTurnsForRename = 12
	// renamerSourceTag is stamped on Source so the renamer's own session
	// (a) gets auto-filed via LLMBRIDGE_SOURCE_FOLDERS, and (b) is excluded
	// from the auto-rename trigger so it doesn't recurse on itself.
	renamerSourceTag = "renamer"
	// renamerStartDelay matches the autoResume wait — Claude Code needs a
	// moment to finish its start handshake before stdin sends will land.
	renamerStartDelay = 2 * time.Second
)

// AutoRenameRequest is the body posted by a renamer session back to
// POST /sessions/{id}/auto-rename. RenamerSessionID is required so the server
// can verify the caller still owns the renamer slot — guards against stale
// renamers clobbering a name the user has since manually set.
type AutoRenameRequest struct {
	DisplayName      string `json:"display_name"`
	RenamerSessionID string `json:"renamer_session_id"`
}

func (s *Server) handleAutoRenameSession(w http.ResponseWriter, r *http.Request) {
	bridgeID := r.PathValue("id")
	var req AutoRenameRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}
	name := strings.TrimSpace(req.DisplayName)
	if name == "" {
		http.Error(w, "display_name is required", http.StatusBadRequest)
		return
	}
	if req.RenamerSessionID == "" {
		http.Error(w, "renamer_session_id is required", http.StatusBadRequest)
		return
	}
	if r := []rune(name); len(r) > 80 {
		name = string(r[:80])
	}
	turnCount, err := s.store.CountUserMessages(bridgeID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if err := s.store.ApplyAutoRename(bridgeID, req.RenamerSessionID, name, turnCount); err != nil {
		http.Error(w, err.Error(), http.StatusConflict)
		return
	}
	sess, err := s.store.GetSession(bridgeID)
	if err != nil {
		http.Error(w, "session not found", http.StatusNotFound)
		return
	}
	writeJSON(w, sess)
}

// maybeAutoRename inspects the target session and, when conditions are met,
// spawns a Claude Code renamer session that will produce a sidebar-friendly
// title and POST it back via /sessions/{id}/auto-rename. Always called as a
// goroutine — long-running, must never block the /send response.
//
// Conditions to fire:
//   - Source != "renamer"  (don't recurse on the helper itself)
//   - InstanceID is bound and the harness is Claude Code
//   - display_name is autogenerated (user hasn't manually renamed)
//   - no renamer is already in flight for this target
//   - first run: turn_count >= renameFirstAfter
//   - subsequent runs: turn_count - named_at_turn >= renameEvery
func (s *Server) maybeAutoRename(bridgeID string) {
	target, err := s.store.GetSession(bridgeID)
	if err != nil {
		return
	}
	if target.Source == renamerSourceTag {
		return
	}
	if target.InstanceID == "" || s.harnessStore == nil {
		return
	}
	// Renamer is Claude-Code-only for now. Other harnesses can be added once
	// we have an equivalent way to spawn a side session that calls back via
	// curl.
	if target.Harness != msg.HarnessClaudeCode {
		return
	}

	autogen, namedAtTurn, inFlight, err := s.store.RenamerState(bridgeID)
	if err != nil {
		log.Printf("[renamer] %s: state lookup: %v", bridgeID, err)
		return
	}
	if !autogen {
		return
	}
	if inFlight != "" {
		// Recover stuck slots when the renamer session is no longer in a state
		// that could plausibly produce a result.
		if !s.renamerStillAlive(inFlight) {
			if err := s.store.ClearRenamerSlot(bridgeID); err != nil {
				log.Printf("[renamer] %s: clear stale slot: %v", bridgeID, err)
				return
			}
		} else {
			return
		}
	}

	turnCount, err := s.store.CountUserMessages(bridgeID)
	if err != nil {
		log.Printf("[renamer] %s: count user messages: %v", bridgeID, err)
		return
	}
	threshold := renameEvery
	if namedAtTurn == 0 {
		threshold = renameFirstAfter
	}
	if turnCount-namedAtTurn < threshold {
		return
	}

	turns, err := s.store.RecentTurnTexts(bridgeID, recentTurnsForRename)
	if err != nil {
		log.Printf("[renamer] %s: load transcript: %v", bridgeID, err)
		return
	}
	if len(turns) == 0 {
		return
	}

	if err := s.spawnRenamerSession(target, turns); err != nil {
		log.Printf("[renamer] %s: spawn failed: %v", bridgeID, err)
	}
}

// renamerStillAlive returns true when a renamer session row exists and is in
// a state that may still produce a result. Used to recover from crashed or
// orphaned renamers.
func (s *Server) renamerStillAlive(renamerID string) bool {
	sess, err := s.store.GetSession(renamerID)
	if err != nil {
		return false
	}
	switch sess.State {
	case string(msg.SessionRunning), string(msg.SessionIdle):
		return true
	default:
		return false
	}
}

// spawnRenamerSession creates a fresh Claude Code session bound to the same
// instance as the target, reserves the renamer slot, starts the harness, and
// pushes the renamer prompt onto its stdin.
func (s *Server) spawnRenamerSession(target *store.Session, turns []store.TurnText) error {
	inst, err := s.harnessStore.GetInstance(target.InstanceID)
	if err != nil {
		return fmt.Errorf("lookup instance: %w", err)
	}
	if !inst.Enabled {
		return fmt.Errorf("instance %s disabled", inst.ID)
	}

	renamer := &store.Session{
		BridgeID:    generateBridgeID(),
		ClientID:    "renamer",
		DisplayName: fmt.Sprintf("rename %s", target.BridgeID),
		Harness:     msg.HarnessClaudeCode,
		InstanceID:  inst.ID,
		State:       string(msg.SessionIdle),
		AgentID:     "session-renamer",
		ParentID:    target.BridgeID,
		Source:      renamerSourceTag,
		FolderName:  s.folderForSource(renamerSourceTag),
	}
	if err := s.store.CreateSession(renamer); err != nil {
		return fmt.Errorf("create session: %w", err)
	}

	ok, err := s.store.ReserveRenamerSlot(target.BridgeID, renamer.BridgeID)
	if err != nil {
		s.store.DeleteSession(renamer.BridgeID)
		return fmt.Errorf("reserve slot: %w", err)
	}
	if !ok {
		// Lost the race to another goroutine; drop the just-created session
		// so we don't leak an empty CC process.
		s.store.DeleteSession(renamer.BridgeID)
		return nil
	}

	credID := resolveCredential(s.harnessStore, inst.ID)
	if _, err := s.startOnInstance(context.Background(), renamer, inst, credID); err != nil {
		s.store.ClearRenamerSlot(target.BridgeID)
		s.store.DeleteSession(renamer.BridgeID)
		return fmt.Errorf("start: %w", err)
	}

	prompt := buildRenamerPrompt(target, renamer.BridgeID, turns, publicBaseURL(s.cfg.ListenAddr))

	// Mirror handleSendMessage: broadcast the user_message so the bubble
	// shows up in the renamer's UI/SSE stream, push to log-store, then write
	// the prompt onto the harness stdin.
	userEvent := msg.Event{
		Type:      msg.EventUserMessage,
		SessionID: renamer.BridgeID,
		BridgeID:  renamer.BridgeID,
		Timestamp: time.Now(),
		Result:    &msg.ResultEvent{Text: prompt},
	}
	if _, err := s.harness.BroadcastEvent(&userEvent); err != nil {
		log.Printf("[renamer] %s: broadcast user_message: %v", renamer.BridgeID, err)
	}
	if err := s.harness.PushEvent(userEvent); err != nil {
		log.Printf("[renamer] %s: push to log-store: %v", renamer.BridgeID, err)
	}

	time.Sleep(renamerStartDelay)
	if err := s.harness.Send(renamer.BridgeID, prompt); err != nil {
		s.store.ClearRenamerSlot(target.BridgeID)
		return fmt.Errorf("send prompt: %w", err)
	}

	log.Printf("[renamer] %s: spawned %s (turns=%d)", target.BridgeID, renamer.BridgeID, len(turns))
	return nil
}

// buildRenamerPrompt produces the single-shot prompt sent to the renamer's
// Claude Code session. It explains the job, embeds the recent transcript,
// and gives the exact curl call the renamer should make on completion.
func buildRenamerPrompt(target *store.Session, renamerID string, turns []store.TurnText, baseURL string) string {
	var b strings.Builder
	b.WriteString("You are an auto-rename helper for a chat session. Read the transcript below and produce a concise sidebar-friendly title for the SOURCE SESSION (not yourself). The title should describe what the session is actually about — the topic, task, or problem being worked on — not the literal first message. Aim for 30–50 characters; the hard limit is 80.\n\n")
	fmt.Fprintf(&b, "SOURCE SESSION bridge_id: %s\n", target.BridgeID)
	fmt.Fprintf(&b, "Current display name: %q\n", target.DisplayName)
	fmt.Fprintf(&b, "Your renamer bridge_id: %s\n\n", renamerID)
	b.WriteString("Transcript (oldest first):\n---\n")
	for i, t := range turns {
		fmt.Fprintf(&b, "Turn %d\n", i+1)
		if t.User != "" {
			fmt.Fprintf(&b, "USER: %s\n", t.User)
		}
		if t.Assistant != "" {
			fmt.Fprintf(&b, "ASSISTANT: %s\n", t.Assistant)
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n\n")
	b.WriteString("When you have decided on a title, post it back via curl:\n\n")
	fmt.Fprintf(&b,
		"curl -sfS -X POST %s/sessions/%s/auto-rename -H 'Content-Type: application/json' -d '{\"display_name\":\"<TITLE>\",\"renamer_session_id\":\"%s\"}'\n\n",
		baseURL, target.BridgeID, renamerID,
	)
	b.WriteString("After the curl returns 200 you are completely done — do not do any further work, do not summarize, do not produce any extra output. Just give a single short confirmation and stop.")
	return b.String()
}
