package server

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
)

// updateReadmeRouteTable rewrites the README's route table instead of
// checking it: go test ./internal/server -run TestReadmeRouteTable -update-readme-route-table
var updateReadmeRouteTable = flag.Bool("update-readme-route-table", false, "rewrite the route table in README.md from routeDescriptions and routeAccessRules")

const (
	readmePath             = "../../README.md"
	readmeRouteTableBegins = "<!-- route-table:begin (generated by TestReadmeRouteTableMatchesTheRoutes; do not edit by hand) -->"
	readmeRouteTableEnds   = "<!-- route-table:end -->"
)

// whoMayCallRoute is the "Who may call" column: the short name of each
// access class. "Who may call what" in the README says what each one means.
var whoMayCallRoute = map[routeAccessClass]string{
	routeOpenToEveryone:                           "anyone",
	routeHarnessCallback:                          "harness callback",
	routeOperatorOnly:                             "operator",
	routePrincipalCreatesSession:                  "principal, as itself",
	routePrincipalOwnsSession:                     "owner",
	routePrincipalOwnsSignal:                      "owner",
	routePrincipalSeesOwnSessionsOnly:             "principal, own sessions only",
	routePrincipalReadsCatalog:                    "principal",
	routePrincipalRefusedCannotBeFiltered:         "operator",
	routePrincipalOrSessionAgentThroughStoreProxy: "principal or session agent",
	routePrincipalCreatesOperation:                "principal, as itself, in its organization",
	routePrincipalOwnsOperation:                   "owner",
	routePrincipalSeesOwnOperationsOnly:           "principal, own operations only",
}

func TestEveryRouteHasADescriptionAndEveryDescriptionARoute(t *testing.T) {
	for pattern := range routeAccessRules {
		if _, described := routeDescriptions[pattern]; !described {
			t.Errorf("%q has an access rule but no entry in routeDescriptions", pattern)
		}
	}
	for pattern, described := range routeDescriptions {
		if _, classified := routeAccessRules[pattern]; !classified {
			t.Errorf("routeDescriptions has %q, which has no access rule", pattern)
		}
		if strings.TrimSpace(described.description) == "" {
			t.Errorf("routeDescriptions[%q] has no description", pattern)
		}
		found := false
		for _, group := range routeGroupsInReadmeOrder {
			found = found || group == described.group
		}
		if !found {
			t.Errorf("routeDescriptions[%q] is in group %q, which routeGroupsInReadmeOrder does not list", pattern, described.group)
		}
	}
	for pattern, rule := range routeAccessRules {
		if _, named := whoMayCallRoute[rule.class]; !named {
			t.Errorf("%q is in access class %d, which whoMayCallRoute does not name", pattern, rule.class)
		}
	}
}

func TestReadmeRouteTableMatchesTheRoutes(t *testing.T) {
	readme, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatal(err)
	}
	before, rest, foundBegin := strings.Cut(string(readme), readmeRouteTableBegins)
	_, after, foundEnd := strings.Cut(rest, readmeRouteTableEnds)
	if !foundBegin || !foundEnd {
		t.Fatalf("README.md has no route table between %q and %q", readmeRouteTableBegins, readmeRouteTableEnds)
	}
	generated := "\n" + generateReadmeRouteTable() + "\n"
	if *updateReadmeRouteTable {
		updated := before + readmeRouteTableBegins + generated + readmeRouteTableEnds + after
		if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	current, _, _ := strings.Cut(rest, readmeRouteTableEnds)
	if current != generated {
		t.Errorf("README.md's route table is not the one routeDescriptions and routeAccessRules produce; run\n  go test ./internal/server -run TestReadmeRouteTable -update-readme-route-table")
	}
}

func generateReadmeRouteTable() string {
	patternsByGroup := map[routeGroup][]string{}
	for pattern, described := range routeDescriptions {
		patternsByGroup[described.group] = append(patternsByGroup[described.group], pattern)
	}
	var table strings.Builder
	for groupIndex, group := range routeGroupsInReadmeOrder {
		patterns := patternsByGroup[group]
		sort.Slice(patterns, func(i, j int) bool {
			methodI, pathI := splitRoutePattern(patterns[i])
			methodJ, pathJ := splitRoutePattern(patterns[j])
			if pathI != pathJ {
				return pathI < pathJ
			}
			return methodI < methodJ
		})
		if groupIndex > 0 {
			table.WriteString("\n")
		}
		fmt.Fprintf(&table, "### %s\n\n", group)
		table.WriteString("| Method | Route | What it does | Who may call |\n|---|---|---|---|\n")
		for _, pattern := range patterns {
			method, path := splitRoutePattern(pattern)
			fmt.Fprintf(&table, "| `%s` | `%s` | %s | %s |\n",
				method, path, routeDescriptions[pattern].description, whoMayCallRoute[routeAccessRules[pattern].class])
		}
	}
	return strings.TrimSuffix(table.String(), "\n")
}

// splitRoutePattern splits "GET /x" into its method and path; a pattern
// registered without a method matches every method, shown as "*".
func splitRoutePattern(pattern string) (method, path string) {
	method, path, hasMethod := strings.Cut(pattern, " ")
	if !hasMethod {
		return "*", pattern
	}
	return method, path
}
